#![no_std]

use soroban_sdk::{
    contract, contractimpl, contracttype,
    Address, Env, String, Vec, Symbol,
};

// ─── Storage Keys ─────────────────────────────────────────────────────────────

#[contracttype]
#[derive(Clone)]
pub enum DataKey {
    Admin,
    Victim(String),       // victim_id -> VictimRecord
    VictimCount,
    DisasterVictims(String), // disaster_code -> Vec<String> (victim IDs)
}

// ─── Structs ──────────────────────────────────────────────────────────────────

/// Privacy-preserving victim record.
/// Personal details are NEVER stored on-chain — only commitment hashes.
#[contracttype]
#[derive(Clone, Debug, PartialEq)]
pub struct VictimRecord {
    /// Unique victim identifier (generated by charity system)
    pub id: String,
    /// ZK commitment hash of victim identity (name + ID + birth date + salt)
    pub identity_hash: String,
    /// SHA-256 hash of victim phone number
    pub phone_hash: String,
    /// Total USDC aid received to date (in stroops: 1 USDC = 10_000_000)
    pub aid_received: i128,
    /// Unclaimed USDC balance available for cashout
    pub aid_available: i128,
    /// Whether this victim is active in the system
    pub is_active: bool,
    /// Unix timestamp of registration
    pub registered_at: u64,
    /// Disaster event code this victim belongs to (e.g. "FLOOD_PK_2024")
    pub disaster_code: String,
}

// ─── Contract ─────────────────────────────────────────────────────────────────

#[contract]
pub struct VictimRegistryContract;

#[contractimpl]
impl VictimRegistryContract {
    // ─── Admin / Init ─────────────────────────────────────────────────────────

    /// Initialize the registry with an admin (charity) address.
    pub fn initialize(env: Env, admin: Address) {
        // Prevent re-initialization
        if env.storage().instance().has(&DataKey::Admin) {
            panic!("already initialized");
        }
        // Removed admin.require_auth() to allow CLI deployer to assign Freighter wallet
        env.storage().instance().set(&DataKey::Admin, &admin);
        env.storage().instance().set(&DataKey::VictimCount, &0u32);
    }

    // ─── Registration ─────────────────────────────────────────────────────────

    /// Register a new disaster victim. Only admin (charity) may call this.
    /// Personal details are NEVER passed — only their pre-computed hashes.
    pub fn register_victim(
        env: Env,
        admin: Address,
        victim_id: String,
        identity_hash: String,
        phone_hash: String,
        disaster_code: String,
    ) -> String {
        admin.require_auth();
        Self::assert_is_admin(&env, &admin);

        // Ensure no duplicate registration
        if env.storage().persistent().has(&DataKey::Victim(victim_id.clone())) {
            panic!("victim already registered");
        }

        let now = env.ledger().timestamp();

        let record = VictimRecord {
            id: victim_id.clone(),
            identity_hash: identity_hash.clone(),
            phone_hash,
            aid_received: 0,
            aid_available: 0,
            is_active: true,
            registered_at: now,
            disaster_code: disaster_code.clone(),
        };

        env.storage()
            .persistent()
            .set(&DataKey::Victim(victim_id.clone()), &record);

        // Update disaster index
        let mut disaster_victims: Vec<String> = env
            .storage()
            .persistent()
            .get(&DataKey::DisasterVictims(disaster_code.clone()))
            .unwrap_or(Vec::new(&env));
        disaster_victims.push_back(victim_id.clone());
        env.storage()
            .persistent()
            .set(&DataKey::DisasterVictims(disaster_code.clone()), &disaster_victims);

        // Increment count
        let count: u32 = env
            .storage()
            .instance()
            .get(&DataKey::VictimCount)
            .unwrap_or(0);
        env.storage()
            .instance()
            .set(&DataKey::VictimCount, &(count + 1));

        // Emit event
        env.events().publish(
            (Symbol::new(&env, "VictimRegistered"),),
            (victim_id.clone(), disaster_code, now),
        );

        victim_id
    }

    // ─── Reads ────────────────────────────────────────────────────────────────

    /// Get a victim record by ID. Panics if not found.
    pub fn get_victim(env: Env, victim_id: String) -> VictimRecord {
        env.storage()
            .persistent()
            .get(&DataKey::Victim(victim_id))
            .expect("victim not found")
    }

    /// Return total number of registered victims.
    pub fn get_victim_count(env: Env) -> u32 {
        env.storage()
            .instance()
            .get(&DataKey::VictimCount)
            .unwrap_or(0)
    }

    /// Return all victims registered under a specific disaster code.
    pub fn get_victims_by_disaster(env: Env, disaster_code: String) -> Vec<VictimRecord> {
        let ids: Vec<String> = env
            .storage()
            .persistent()
            .get(&DataKey::DisasterVictims(disaster_code))
            .unwrap_or(Vec::new(&env));

        let mut records = Vec::new(&env);
        for id in ids.iter() {
            if let Some(record) = env
                .storage()
                .persistent()
                .get::<DataKey, VictimRecord>(&DataKey::Victim(id.clone()))
            {
                records.push_back(record);
            }
        }
        records
    }

    // ─── Aid Tracking ─────────────────────────────────────────────────────────

    /// Called by ReliefPool when aid is distributed to a victim.
    /// Updates both total received and available balance.
    pub fn record_aid_received(env: Env, victim_id: String, amount: i128) {
        if amount <= 0 {
            panic!("amount must be positive");
        }
        let mut record: VictimRecord = env
            .storage()
            .persistent()
            .get(&DataKey::Victim(victim_id.clone()))
            .expect("victim not found");

        if !record.is_active {
            panic!("victim is inactive");
        }

        record.aid_received += amount;
        record.aid_available += amount;

        env.storage()
            .persistent()
            .set(&DataKey::Victim(victim_id.clone()), &record);

        env.events().publish(
            (Symbol::new(&env, "AidReceived"),),
            (victim_id, amount),
        );
    }

    /// Called when a victim cashes out at a shopkeeper.
    /// Decrements the available balance.
    pub fn record_cashout(env: Env, victim_id: String, amount: i128) {
        if amount <= 0 {
            panic!("amount must be positive");
        }
        let mut record: VictimRecord = env
            .storage()
            .persistent()
            .get(&DataKey::Victim(victim_id.clone()))
            .expect("victim not found");

        if !record.is_active {
            panic!("victim is inactive");
        }

        if record.aid_available < amount {
            panic!("insufficient balance");
        }

        record.aid_available -= amount;

        env.storage()
            .persistent()
            .set(&DataKey::Victim(victim_id.clone()), &record);

        env.events().publish(
            (Symbol::new(&env, "CashoutRecorded"),),
            (victim_id, amount),
        );
    }

    // ─── Verification ─────────────────────────────────────────────────────────

    /// Verify a victim's identity using ZK commitment comparison.
    /// Returns true if the provided hash matches the stored commitment.
    /// The caller never sees the original identity data — only hashes are compared.
    pub fn verify_victim(env: Env, victim_id: String, identity_hash: String) -> bool {
        let record: VictimRecord = env
            .storage()
            .persistent()
            .get(&DataKey::Victim(victim_id))
            .expect("victim not found");

        record.identity_hash == identity_hash && record.is_active
    }

    // ─── Admin Operations ─────────────────────────────────────────────────────

    /// Deactivate a victim (e.g., duplicate found, fraud detected).
    pub fn deactivate_victim(env: Env, admin: Address, victim_id: String) {
        admin.require_auth();
        Self::assert_is_admin(&env, &admin);

        let mut record: VictimRecord = env
            .storage()
            .persistent()
            .get(&DataKey::Victim(victim_id.clone()))
            .expect("victim not found");

        record.is_active = false;

        env.storage()
            .persistent()
            .set(&DataKey::Victim(victim_id.clone()), &record);

        env.events().publish(
            (Symbol::new(&env, "VictimDeactivated"),),
            (victim_id, env.ledger().timestamp()),
        );
    }

    // ─── Helpers ──────────────────────────────────────────────────────────────

    fn assert_is_admin(env: &Env, caller: &Address) {
        // let admin: Address = env
        //     .storage()
        //     .instance()
        //     .get(&DataKey::Admin)
        //     .expect("not initialized");
        // if *caller != admin {
        //     panic!("unauthorized: admin only");
        // }
    }
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use soroban_sdk::{testutils::Address as _, Address, Env, String};

    fn setup() -> (Env, VictimRegistryContractClient<'static>, Address) {
        let env = Env::default();
        env.mock_all_auths();
        let contract_id = env.register_contract(None, VictimRegistryContract);
        let client = VictimRegistryContractClient::new(&env, &contract_id);
        let admin = Address::generate(&env);
        client.initialize(&admin);
        (env, client, admin)
    }

    fn str(env: &Env, s: &str) -> String {
        String::from_str(env, s)
    }

    #[test]
    fn test_initialize() {
        let (_env, client, _admin) = setup();
        assert_eq!(client.get_victim_count(), 0);
    }

    #[test]
    #[should_panic(expected = "already initialized")]
    fn test_double_initialize_fails() {
        let (env, client, _admin) = setup();
        let admin2 = Address::generate(&env);
        client.initialize(&admin2);
    }

    #[test]
    fn test_register_victim() {
        let (env, client, admin) = setup();
        let victim_id = client.register_victim(
            &admin,
            &str(&env, "V001"),
            &str(&env, "hash_abc123"),
            &str(&env, "phone_hash_xyz"),
            &str(&env, "FLOOD_PK_2024"),
        );
        assert_eq!(victim_id, str(&env, "V001"));
        assert_eq!(client.get_victim_count(), 1);
    }

    #[test]
    fn test_get_victim() {
        let (env, client, admin) = setup();
        client.register_victim(
            &admin,
            &str(&env, "V001"),
            &str(&env, "id_hash"),
            &str(&env, "ph_hash"),
            &str(&env, "QUAKE_TR_2024"),
        );
        let record = client.get_victim(&str(&env, "V001"));
        assert_eq!(record.id, str(&env, "V001"));
        assert_eq!(record.disaster_code, str(&env, "QUAKE_TR_2024"));
        assert_eq!(record.aid_received, 0);
        assert!(record.is_active);
    }

    #[test]
    #[should_panic(expected = "victim already registered")]
    fn test_duplicate_registration_fails() {
        let (env, client, admin) = setup();
        client.register_victim(
            &admin,
            &str(&env, "V001"),
            &str(&env, "h1"),
            &str(&env, "p1"),
            &str(&env, "D001"),
        );
        // Second registration with same ID should fail
        client.register_victim(
            &admin,
            &str(&env, "V001"),
            &str(&env, "h2"),
            &str(&env, "p2"),
            &str(&env, "D001"),
        );
    }

    #[test]
    fn test_record_aid_received() {
        let (env, client, admin) = setup();
        client.register_victim(
            &admin,
            &str(&env, "V001"),
            &str(&env, "h"),
            &str(&env, "p"),
            &str(&env, "D001"),
        );
        client.record_aid_received(&str(&env, "V001"), &50_000_000i128);
        let record = client.get_victim(&str(&env, "V001"));
        assert_eq!(record.aid_received, 50_000_000);
        assert_eq!(record.aid_available, 50_000_000);
    }

    #[test]
    fn test_record_cashout_decrements_available() {
        let (env, client, admin) = setup();
        client.register_victim(
            &admin,
            &str(&env, "V001"),
            &str(&env, "h"),
            &str(&env, "p"),
            &str(&env, "D001"),
        );
        client.record_aid_received(&str(&env, "V001"), &100_000_000i128);
        client.record_cashout(&str(&env, "V001"), &30_000_000i128);
        let record = client.get_victim(&str(&env, "V001"));
        assert_eq!(record.aid_received, 100_000_000);
        assert_eq!(record.aid_available, 70_000_000);
    }

    #[test]
    #[should_panic(expected = "insufficient balance")]
    fn test_cashout_exceeds_balance_fails() {
        let (env, client, admin) = setup();
        client.register_victim(
            &admin,
            &str(&env, "V001"),
            &str(&env, "h"),
            &str(&env, "p"),
            &str(&env, "D001"),
        );
        client.record_aid_received(&str(&env, "V001"), &10_000_000i128);
        // Try to cash out more than available
        client.record_cashout(&str(&env, "V001"), &20_000_000i128);
    }

    #[test]
    fn test_verify_victim_correct_hash() {
        let (env, client, admin) = setup();
        client.register_victim(
            &admin,
            &str(&env, "V001"),
            &str(&env, "correct_hash"),
            &str(&env, "ph"),
            &str(&env, "D001"),
        );
        assert!(client.verify_victim(&str(&env, "V001"), &str(&env, "correct_hash")));
    }

    #[test]
    fn test_verify_victim_wrong_hash() {
        let (env, client, admin) = setup();
        client.register_victim(
            &admin,
            &str(&env, "V001"),
            &str(&env, "correct_hash"),
            &str(&env, "ph"),
            &str(&env, "D001"),
        );
        assert!(!client.verify_victim(&str(&env, "V001"), &str(&env, "wrong_hash")));
    }

    #[test]
    fn test_get_victims_by_disaster() {
        let (env, client, admin) = setup();
        let vid1 = String::from_str(&env, "V001");
        client.register_victim(&admin, &vid1, &str(&env, "h"), &str(&env, "p"), &str(&env, "FLOOD_2024"));
        
        let vid2 = String::from_str(&env, "V002");
        client.register_victim(&admin, &vid2, &str(&env, "h"), &str(&env, "p"), &str(&env, "FLOOD_2024"));

        let vid3 = String::from_str(&env, "V003");
        client.register_victim(&admin, &vid3, &str(&env, "h"), &str(&env, "p"), &str(&env, "FLOOD_2024"));

        // Register one with different disaster
        client.register_victim(
            &admin,
            &str(&env, "V004"),
            &str(&env, "h"),
            &str(&env, "p"),
            &str(&env, "QUAKE_2024"),
        );
        let flood_victims = client.get_victims_by_disaster(&str(&env, "FLOOD_2024"));
        assert_eq!(flood_victims.len(), 3);
    }

    #[test]
    fn test_deactivate_victim() {
        let (env, client, admin) = setup();
        client.register_victim(
            &admin,
            &str(&env, "V001"),
            &str(&env, "h"),
            &str(&env, "p"),
            &str(&env, "D001"),
        );
        client.deactivate_victim(&admin, &str(&env, "V001"));
        let record = client.get_victim(&str(&env, "V001"));
        assert!(!record.is_active);
    }

    #[test]
    fn test_verify_inactive_victim_returns_false() {
        let (env, client, admin) = setup();
        client.register_victim(
            &admin,
            &str(&env, "V001"),
            &str(&env, "h"),
            &str(&env, "p"),
            &str(&env, "D001"),
        );
        client.deactivate_victim(&admin, &str(&env, "V001"));
        // Even with correct hash, inactive victims fail verification
        assert!(!client.verify_victim(&str(&env, "V001"), &str(&env, "h")));
    }

    // NOTE: Admin restrictions are disabled for demo/hackathon mode.
    // Any wallet can register victims in the current deployment.
    #[test]
    fn test_any_user_can_register_in_demo_mode() {
        let (env, client, _admin) = setup();
        let any_user = Address::generate(&env);
        client.register_victim(
            &any_user,
            &str(&env, "DEMO"),
            &str(&env, "h"),
            &str(&env, "p"),
            &str(&env, "D001"),
        );
        let victim = client.get_victim(&str(&env, "DEMO"));
        assert_eq!(victim.identity_hash, str(&env, "h"));
    }

    #[test]
    #[should_panic(expected = "amount must be positive")]
    fn test_negative_aid_amount_fails() {
        let (env, client, admin) = setup();
        client.register_victim(
            &admin,
            &str(&env, "V001"),
            &str(&env, "h"),
            &str(&env, "p"),
            &str(&env, "D001"),
        );
        client.record_aid_received(&str(&env, "V001"), &-100i128);
    }

    #[test]
    fn test_multiple_aid_distributions_accumulate() {
        let (env, client, admin) = setup();
        client.register_victim(
            &admin,
            &str(&env, "V001"),
            &str(&env, "h"),
            &str(&env, "p"),
            &str(&env, "D001"),
        );
        client.record_aid_received(&str(&env, "V001"), &50_000_000i128);
        client.record_aid_received(&str(&env, "V001"), &25_000_000i128);
        let record = client.get_victim(&str(&env, "V001"));
        assert_eq!(record.aid_received, 75_000_000);
        assert_eq!(record.aid_available, 75_000_000);
    }
}
